server:
  port: 8080
management:
  server:
    port: 8080
  endpoints:
    enabled-by-default: false
    web:
      base-path: "/"
      path-mapping:
        health: "healthcheck"
  endpoint:
    health:
      enabled: true
      probes.enabled: true