server:
  tomcat:
    threads:
      min-spare: 10
      max: 200
  address: 0.0.0.0
  port: 8080
management:
  server:
    port: 8080
  endpoints:
    enabled-by-default: false
    web:
      base-path: "/"
      path-mapping:
        health: "healthcheck"
  endpoint:
    health:
      enabled: true
      probes.enabled: true